#!/bin/bash

echo "=== 手动获取 BOSS Cookie ==="
echo ""
echo "方法一：使用浏览器扩展（推荐）"
echo "1. 安装 Cookie 编辑器扩展："
echo "   Chrome: https://chrome.google.com/webstore/detail/editthiscookie/fngmhnnpilhplaeedifhccceomclgfbg"
echo "   Firefox: https://addons.mozilla.org/en-US/firefox/addon/cookie-quick-manager/"
echo ""
echo "2. 打开浏览器，访问 https://www.zhipin.com 并登录"
echo "3. 点击扩展图标，导出 Cookie 为 JSON 格式"
echo "4. 复制 JSON，粘贴到 http://127.0.0.1:4173 的「BOSS 登录态」页面"
echo ""
echo "方法二：使用开发者工具"
echo "1. 打开浏览器，访问 https://www.zhipin.com 并登录"
echo "2. 按 F12 打开开发者工具"
echo "3. 切换到 Application → Cookies → https://www.zhipin.com"
echo "4. 复制所有 Cookie（格式：[{\"name\":\"...\",\"value\":\"...\",\"domain\":\".zhipin.com\"},...])"
echo "5. 粘贴到 http://127.0.0.1:4173 的「BOSS 登录态」页面"
echo ""
echo "完成后，在 http://127.0.0.1:4173 点击「执行投递」即可"
