#!/bin/bash

echo "=== 海投助手 - 启动指南 ==="
echo ""

# 检查 Node.js 版本
NODE_VERSION=$(node -v | cut -d'v' -f2 | cut -d'.' -f1-2)
REQUIRED_VERSION="20.16"

if [ "$NODE_VERSION" != "$REQUIRED_VERSION" ]; then
    echo "⚠️  Node.js 版本不匹配"
    echo "当前版本: $NODE_VERSION"
    echo "需要版本: $REQUIRED_VERSION"
    echo ""
    echo "请使用 Volta 切换到正确的版本："
    echo "  volta install node@20.16.0"
    echo ""
fi

echo "=== 启动选项 ==="
echo ""
echo "1. 启动 Web 版本（当前项目）"
echo "   cd /Users/kven/Desktop/Project/海投助手/haitou-assistant-next"
echo "   node src/server.js"
echo ""
echo "   然后访问: http://127.0.0.1:4173"
echo ""
echo "   功能："
echo "   ✅ 职位采集（真实 BOSS 数据）"
echo "   ✅ 筛选规则"
echo "   ✅ 候选管理"
echo "   ✅ 数据统计"
echo "   ⚠️  自动投递（受 BOSS 反爬虫限制）"
echo ""
echo "2. 使用原始 GeekGeekRun 应用（推荐用于自动投递）"
echo "   位置: /Applications/GeekGeekRun.app"
echo ""
echo "   功能："
echo "   ✅ 完整自动化投递"
echo "   ✅ 已读不回自动复聊"
echo "   ✅ Cookie 管理"
echo "   ✅ GUI 界面"
echo ""
echo "=== 推荐工作流程 ==="
echo ""
echo "1. 使用 Web 版本进行职位采集和筛选"
echo "   - 高效采集 BOSS 职位"
echo "   - 灵活筛选候选"
echo "   - 确认投递目标"
echo ""
echo "2. 导出候选列表"
echo "   - 点击「导出数据」按钮"
echo "   - 保存为 JSON 文件"
echo ""
echo "3. 使用原始应用进行自动投递"
echo "   - 在原始应用中导入数据"
echo "   - 执行自动投递"
echo ""
echo "=== 或者：Cookie 共享方案 ==="
echo ""
echo "1. 在 Web 版本中配置 Cookie"
echo "   - 访问 BOSS 直聘并登录"
echo "   - 使用 EditThisCookie 导出 Cookie"
echo "   - 粘贴到 Web 版本的「BOSS 登录态」"
echo ""
echo "2. Cookie 自动保存到共享位置"
echo "   ~/.geekgeekrun/storage/boss-cookies.json"
echo ""
echo "3. 原始应用和 Web 版本都可以使用这个 Cookie"
echo ""
